version: '2.1'

services:
  api-toolbox-messages:
    image: api-toolbox-messages
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080